name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  check-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Install utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Check if coverage-summary.json exists
        run: |
          echo "Listing coverage files for verification:"
          ls ./coverage
          if [ ! -f ./coverage/coverage-summary.json ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          echo "Coverage report found"

      - name: Check test coverage
        run: |
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, cannot proceed."
            exit 1
          fi
